services:
  asterisk:
    container_name: asterisk
    restart: unless-stopped
    image: andrius/asterisk:18-current
    network_mode: host
    volumes:
      - /mnt/TANK/docker/asterisk/etc:/etc/asterisk
      - /mnt/TANK/docker/asterisk/var/sounds:/var/lib/asterisk/sounds
      - /mnt/TANK/docker/asterisk/var/keys:/var/lib/asterisk/keys
    ports:
      # SIP signaling
      - "5060:5060/udp"
      - "5060:5060/tcp"
      # RTP media ports
      - "10000-10100:10000-10100/udp" # RTP media
      # Asterisk Manager Interface
      - "5038:5038/tcp"
    environment:
      - TZ=UTC
      - ASTERISK_UID=1000
      - ASTERISK_GID=1000
