services:
  asterisk:
    container_name: asterisk
    restart: unless-stopped
    image: andrius/asterisk
    volumes:
      - /mnt/TANK/docker/asterisk/etc:/etc/asterisk
      - /mnt/TANK/docker/asterisk/var:/var/lib/asterisk
      - /mnt/TANK/docker/asterisk/var/sounds:/var/lib/asterisk/sounds
    ports:
      - "5060:5060/udp"               # SIP signaling
      - "10000-10010:10000-10010/udp" # RTP media
    environment:
      - TZ=UTC
